//=======================================================================================================================
//Copyright(C) 2021 Matvey Safroshkin, Grigory Arutyunov, Patrick Mueller
//Computer Vision Studio
//Friedrich Miescher Laboratory of the Max Planck Society
//Systems Biology of Development, University of Konstanz
//This software is distributed under the terms of the GNU General Public License
//=======================================================================================================================

#include "AnnoWidget.h"

#include <QResizeEvent>
#include <qsizepolicy.h>

#include <stdexcept>

AnnoWidget::AnnoWidget(QWidget* parent): QOpenGLWidget(parent), 
    m_program_arrows(nullptr), m_program_boxes(nullptr), m_program_frame(nullptr)
{
    const int minimumHeight = 600;
    const int minimumWidth = 600;

    const int defaultWidth = 600;
    const int defaultHeight = 600;

    this->setMinimumHeight(minimumHeight);
    this->setMinimumWidth(minimumWidth);
    this->resize(defaultWidth, defaultHeight);
    this->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
}

AnnoWidget::~AnnoWidget()
{
    delete m_frame;
    delete m_program_arrows;
    delete m_program_boxes;
    delete m_program_frame;
}

void AnnoWidget::setImage(const QImage& img)
{
    try
    {
        m_img = img;
        if (m_img.isNull())
        {
            return;
        }
        
        this->updateFrame(img.mirrored());

        this->repaint();
    }
    catch (std::exception e)
    {
        std::string str = e.what();
    }

 }

void AnnoWidget::setArrows(const QList<QVector2D>& positions, const QList<QVector3D>& rotations)
{
    m_positions = positions;
    m_rotations = rotations;

    for (QVector2D& position: m_positions)
    {
        position.setX(position.x() * width());
        position.setY(position.y() * height());
    }

    if (positions.size() != rotations.size()) 
    {
        throw std::runtime_error("GLWidget: positions.size() != rotations.size()");
    }

    update();
}

void AnnoWidget::initializeGL()
{
    initializeOpenGLFunctions();

    QString shaders_dir = "C:/Users/User/Downloads/Telegram Desktop/shaders/";

    // Shader to render arrows, arrows are renderen using a full-screen quad
    m_program_arrows = new QOpenGLShaderProgram(this);
    loadShaderFromFile(m_program_arrows, QOpenGLShader::Vertex, shaders_dir + QString("quad.vert"));
    loadShaderFromFile(m_program_arrows, QOpenGLShader::Fragment, shaders_dir + QString("draw_arrow.frag"));
    m_program_arrows->link();

    // Shader to render boxes, boxes are generated by the geometry shader. As a seed, a single vertex is used
    m_program_boxes = new QOpenGLShaderProgram(this);
    loadShaderFromFile(m_program_boxes, QOpenGLShader::Vertex, shaders_dir + QString("empty.vert"));
    loadShaderFromFile(m_program_boxes, QOpenGLShader::Geometry, shaders_dir + QString("generate_box.geom"));
    loadShaderFromFile(m_program_boxes, QOpenGLShader::Fragment, shaders_dir + QString("paint_color.frag"));
    m_program_boxes->link();

    // Shader to render background image. Like arrows, the bg image is rendered on  full-screen quad
    m_program_frame = new QOpenGLShaderProgram(this);
    loadShaderFromFile(m_program_frame, QOpenGLShader::Vertex, shaders_dir + QString("quad.vert"));
    loadShaderFromFile(m_program_frame, QOpenGLShader::Fragment, shaders_dir + QString("paint_texture.frag"));
    m_program_frame->link();

    // --------------------------------------------------------------------------------------------
    // Vertex data for the full-screen quad
    GLfloat quad_vertices[] = {
        // Positions      // Texture Coords
       -1.f,  1.f, .0f,   0.0f, 1.0f,
       -1.f, -1.f, .0f,   0.0f, 0.0f,
        1.f, -1.f, .0f,   1.0f, 0.0f,

       -1.f,  1.f, .0f,   0.0f, 1.0f,
        1.f, -1.f, .0f,   1.0f, 0.0f,
        1.f,  1.f, .0f,   1.0f, 1.0f
    };

    // Initialize Vertex Attributes Object for the full-screen quad

    m_VAO_quad.create();
    m_VAO_quad.bind();

    m_VBO_quad.create();
    m_VBO_quad.bind();

    glBufferData(GL_ARRAY_BUFFER, sizeof(quad_vertices), &quad_vertices, GL_STATIC_DRAW);

    // Vertices position attribute
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 5 * sizeof(GLfloat), (GLvoid*)0);
    glEnableVertexAttribArray(0);

    // Texture Coordinate attribute
    glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 5 * sizeof(GLfloat), (GLvoid*)(3 * sizeof(GLfloat)));
    glEnableVertexAttribArray(1);

    m_VBO_quad.release();
    m_VAO_quad.release();

    // --------------------------------------------------------------------------------------------
    // Initialize Vertex Attributes Object for a single point to render boxes later
    GLfloat point[] = { 0.f, 0.f, 0.f };

    m_VAO_1.create();
    m_VAO_1.bind();

    m_VBO_1.create();
    m_VBO_1.bind();
    m_VBO_1.allocate(point, sizeof(point));
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(float), nullptr);
    m_VBO_1.release();

    m_VAO_1.release();

    // --------------------------------------------------------------------------------------------
    QImage image_init(1, 1, QImage::Format_RGBA8888);
    image_init.setPixel(0, 0, QColor(127, 127, 127, 255).rgba());

    m_frame = createTexture(image_init);
}

void AnnoWidget::paintGL()
{
    QVector2D resolution(width(), height());

    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    if (m_frame != nullptr)
    {
        // Render image
        m_VAO_quad.bind();
        m_program_frame->bind();
        m_frame->bind();
        glActiveTexture(GL_TEXTURE0);
        m_program_frame->setUniformValue("screenTexture", 0);
        glDrawArrays(GL_TRIANGLES, 0, 6);
        m_program_frame->release();
    }

    if (!m_rotations.isEmpty())
    {
        // Render arrows
        m_VAO_quad.bind();
        m_program_arrows->bind();
        for (qsizetype i = 0; i < m_rotations.size(); i++) {
            m_program_arrows->setUniformValue("rotation", m_rotations[i]);
            m_program_arrows->setUniformValue("position", m_positions[i]);
            m_program_arrows->setUniformValue("resolution", resolution);

            glDrawArrays(GL_TRIANGLES, 0, 6);
        }
        m_program_arrows->release();
        m_VAO_quad.release();
    }

    glDisable(GL_BLEND);
}

void AnnoWidget::resizeEvent(QResizeEvent* event)
{
    QSize size = event->size();
    QSize correctSize = QSize(std::max(size.width(), size.height()), std::max(size.width(), size.height())); // this one causes that behaviour .
    this->resize(correctSize);
    this->setImage(m_img);
    QOpenGLWidget::resizeEvent(event);
}

void AnnoWidget::resizeGL(int w, int h)
{
    if (m_width * m_height > 0)
    {
        const float scaleX = static_cast<float>(w) / static_cast<float>(m_width);
        const float scaleY = static_cast<float>(h) / static_cast<float>(m_height);

        for (QVector2D& position : m_positions)
        {
            position.setX(position.x() * scaleX);
            position.setY(position.y() * scaleY);
        }

    }

    m_width = w;
    m_height = h;

    glViewport(0, 0, w, h);
}

void AnnoWidget::updateFrame(const QImage& frame)
{
    if (!m_frame || frame.width() != m_frame->width() || frame.height() != m_frame->height())
    {
        // Delete the existing texture if it doesn't match the dimensions of the new texture
        m_frame->release();
        delete m_frame;
        m_frame = createTexture(frame.convertToFormat(QImage::Format_RGBA8888)); // Create a new texture
    }
    else
    {
        m_frame->setData(frame.convertToFormat(QImage::Format_RGBA8888)); // Update the existing texture
    }
}

QOpenGLTexture* AnnoWidget::createTexture(const QImage& image)
{
    QOpenGLTexture* texture = new QOpenGLTexture(image.mirrored());
    texture->setSize(width(), height());
    texture->setFormat(QOpenGLTexture::RGBA8_UNorm);
    texture->allocateStorage();

    texture->setMinificationFilter(QOpenGLTexture::Linear);
    texture->setMagnificationFilter(QOpenGLTexture::Linear);
    return texture;
}

bool AnnoWidget::loadShaderFromFile(QOpenGLShaderProgram* program, QOpenGLShader::ShaderType type, const QString& filePath)
{
    const QString shaderSource = readFile(filePath);
    if (shaderSource.isEmpty())
    {
        std::string shaderTypeStr;
        switch (type)
        {
        case QOpenGLShader::Vertex:
            shaderTypeStr = "vertex";
            break;
        case QOpenGLShader::Fragment:
            shaderTypeStr = "fragment";
            break;
        case QOpenGLShader::Geometry:
            shaderTypeStr = "geometry";
            break;
        }
        throw std::runtime_error("Could not load shader file of type" + shaderTypeStr);
    }
    return program->addShaderFromSourceCode(type, shaderSource);
}


QString AnnoWidget::readFile(const QString& filePath)
{
    QFile file(filePath);

    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();

    QTextStream in(&file);
    QString content = in.readAll();
    file.close();

    return content;
}

void AnnoWidget::mouseReleaseEvent(QMouseEvent* event)
{
    if (m_img.isNull())
    {
        return;
    }
    const QPoint pos = event->pos();
    const QPoint resizedPos = QPoint(pos.x() * (static_cast<double>(m_img.width()) / static_cast<double>(this->width())),
        pos.y()* (static_cast<double>(m_img.height()) / static_cast<double>(this->height())));
    if (event->button() == Qt::LeftButton) {
        emit sendLeftClick(resizedPos);
    }

    if (event->button() == Qt::MiddleButton) {
        emit wheelPress(resizedPos);
    }
    if (event->button() == Qt::RightButton) {
        emit sendRightClick(resizedPos);
    }

}

void AnnoWidget::wheelEvent(QWheelEvent* event)
{
    if (m_img.isNull())
    {
        return;
    }

    const QPoint pos = event->pos();
    const QPoint resizedPos = QPoint(pos.x() * (static_cast<double>(m_img.width()) / static_cast<double>(this->width())),
        pos.y()* (static_cast<double>(m_img.height()) / static_cast<double>(this->height())));
    emit sendWheelRotation(resizedPos, event->angleDelta() / 8 / 3);
}


/*
void AnnoWidget::keyPressEvent( QKeyEvent* e)
{
    emit(sendKey(e));
}*/