; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RotationFishLabeler"
#define MyAppVersion "1.0"
#define MyAppPublisher "Computer VIsion Studio"
#define MyAppExeName "RotationFishLabeler.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D0402B9F-9CAE-4608-B7E6-27214ACBC599}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=RotationFIleLabeler
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\imageformats\*"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\platforms\*"; DestDir: "{app}\platforms\"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\RotationFishLabeler\shaders\*"; DestDir: "{app}\shaders\"; Flags: ignoreversion
Source: "C:\work\VMShared\Win10Pro\VC\VC_redist.x64.exe"; DestDir: {tmp}; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: {tmp}\VC_redist.x64.exe; \
    Parameters: "/q /passive /norestart /Q:a /c:""msiexec /q /i vcredist.msi"""; \
    StatusMsg: "Installing VC++ 2015-2019 Redistributables..."

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

